-- SELECT * FROM db_api_plans;
-- SELECT * FROM db_api_clients;
-- SELECT * FROM db_api_alarms;
SELECT * FROM db_api_ports;
-- 
-- 
-- INSERT table (user_name, password) VALUES ('usr', 'pass'),('usr', 'pass');
-- 
-- UPDATE table SET field='val' WHERE pk='val'
-- 
-- DELETE FROM table WHERE pk='val';